# Generated by Django 5.0.3 on 2024-05-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_users_user_id_1cecd0_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
