# Generated by Django 5.0.3 on 2024-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='readed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
